context:
  version: "1.0.0"

package:
  name: compose-language-service
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@microsoft/compose-language-service/-/compose-language-service-${{ version }}.tgz
  sha256: a05c72415a94db9ebcbf51f99eca082f93d99e1e78ae4bd3d187eda6832c9d5f

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "docker-compose-langserver 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Language service for Docker Compose documents
  homepage: https://github.com/microsoft/compose-language-service
  repository: https://github.com/microsoft/compose-language-service

extra:
  recipe-maintainers:
    - danielnachun
